
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: rxai-git-pipeline-parametrizable-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: repo-url
      value: https://github.com/jmontalvof/rxai.git
    - name: script
      value: main.py
  templates:
    - name: main
      inputs:
        parameters:
        - name: repo-url
        - name: script
      container:
        image: python:3.9
        command: ["sh", "-c"]
        args:
          - |
            apt update && apt install -y git python3-pip &&
            git clone {{inputs.parameters.repo-url}} repo &&
            cd repo &&
            pip install -r requirements.txt || true &&
            python3 {{inputs.parameters.script}}
